name: tekaly_lyrics
description: Tekartik lyrics parser
version: 1.1.2
publish_to: none

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  meta: ">=1.15.0"
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
  tekartik_midi:
    git:
      url: https://github.com/tekartik/midi.dart
  # path: ^1.8.0

dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"
resolution: workspace
