name: tekaly_lyrics
description: Tekartik lyrics parser
version: 1.0.1
publish_to: none

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  meta: ">=1.15.0"
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
  tekartik_midi:
    git:
      url: https://github.com/tekartik/midi.dart
      ref: dart3a
  # path: ^1.8.0

dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"
